getstarted=//button[contains(text(),"Get Started")]
email=//input[@placeholder="Enter Login ID or Mobile Number"]
next=//button[contains(text()," Next ")]
password=//input[@placeholder="Password"]
customercode=//input[@placeholder="Customer Code"]
login=//button[contains(text(),"Login")]
menu=//img[@src="assets/imgs/ic_ham.png"]
master=(//ion-row[@class="ion-no-padding center_item md hydrated"])[3]
ccmaster=(//ion-row[@class="ion-no-padding center_item md hydrated"])[5]
navbutton=//img[@src="assets/imgs/ic_back.png"]
header=(//div[@class="block_center_content"])[2]
Dashboard=//div[@class="block_center_content"]
searchbar_displayed=//div[@class="search-bar-platform"]
searchinput=//input[@class="search-bar-platform__input"]
search_closebutton1=//*[@id="searchPage-searchCatalogue"]/ion-icon
td=//table[@class="report-table"]
nodatafound=//h1[@style="text-align: center;"]
seachdataintable1=style="text-align: left; vertical-align: top;"
searchdataintable2=(//td[@style="text-align: left; vertical-align: top;"])[2]
searchdataintable3=style="text-align: left; vertical-align: top;"
searchclosebutton=//ion-icon[@class="search-bar-platform__clearInputIcon md hydrated"]
chcfilter=(//div[@class="ionic-selectable-value-item"])[2]
clickchcfilter=//button[@class='ionic-selectable-cover']
CHClistheader=//span[normalize-space()='Chilling Center']
checkbox=//ion-icon[@aria-label="checkmark circle"]
buttons=//ion-button[@class="md button button-solid ion-activatable ion-focusable hydrated"]
addcollectioncenter=(//ion-button[@class="md button button-solid ion-activatable ion-focusable hydrated"])[1]
backbuttononform=//app-chilling-collection-farmer-edit[@class='ion-page can-go-back']//img
ccform=//p[normalize-space()='Create Collection Center Form']
instructionicon=//div[@class=\\"instructionButton\\"]
Instructionttext=//ion-content[@class="ion-padding md content-sizing content-ltr hydrated"]
fieldinccform=//ion-col[@class="formControlLabel md hydrated"]
inputype=//input[@class="native-input sc-ion-input-md"]
selectedchconform=//*[@id="cardContent"]/form/ion-grid/ion-row[3]/ion-col[3]/div/ion-item
cancel=//ion-button[@class="ion-color ion-color-danger md button button-small button-round button-solid ion-activatable ion-focusable hydrated"]
reset=//ion-button[@class="ion-color ion-color-warning md button button-small button-round button-solid ion-activatable ion-focusable hydrated"]
senddata_input=//input[@placeholder='Enter Value']
cc_Code=//*[@id="cardContent"]/form/ion-grid/ion-row[1]/ion-col[3]/ion-input
cc_Name=//*[@id="cardContent"]/form/ion-grid/ion-row[2]/ion-col[3]/ion-input
PCC_Code=//*[@id="cardContent"]/form/ion-grid/ion-row[4]/ion-col[3]/ion-input
Address=//*[@id="cardContent"]/form/ion-grid/ion-row[5]/ion-col[3]/ion-input
Manager=//*[@id="cardContent"]/form/ion-grid/ion-row[6]/ion-col[3]/ion-input
Mobile=//*[@id="cardContent"]/form/ion-grid/ion-row[7]/ion-col[3]/ion-input
Bank_Name=//*[@id="cardContent"]/form/ion-grid/div[1]/ion-row[1]/ion-col[3]/ion-input
Branch_Name=//*[@id="cardContent"]/form/ion-grid/div[1]/ion-row[2]/ion-col[3]/ion-input
IFSC=//*[@id="cardContent"]/form/ion-grid/div[1]/ion-row[3]/ion-col[3]/ion-input
Acc_NUmber=//*[@id="cardContent"]/form/ion-grid/div[1]/ion-row[4]/ion-col[3]/ion-input
Acc_HName=//*[@id="cardContent"]/form/ion-grid/div[1]/ion-row[5]/ion-col[3]/ion-input
ID_Type=//*[@id="cardContent"]/form/ion-grid/div[2]/ion-row[1]/ion-col[3]/ion-input
ID_Number=//*[@id="cardContent"]/form/ion-grid/div[2]/ion-row[2]/ion-col[3]/ion-input
Superviser_Login=//*[@id="cardContent"]/form/ion-grid/ion-row[8]/ion-col[3]/ion-input
Submit=//ion-button[@class="md button button-small button-round button-solid ion-activatable ion-focusable hydrated"]
toastmessage=//ion-toast[@class="md hydrated"]
errormessage=//*[@id="cardContent"]/form/ion-grid/ion-row/ion-col/p
table=table
tablerow=//*[@id="content"]/app-master-organisation-creation/ion-content/div/div[4]/table/tbody/tr[3]/td[2]/div/p[2]/b
tabledata=//*[@id="content"]/app-master-organisation-creation/ion-content/div/div[4]/table/tbody/tr[3]/td[2]/div/p[2]/b
Selected_chc=//ionic-selectable[@class="ionic-selectable ionic-selectable-is-enabled ionic-selectable-md ng-pristine ng-valid ionic-selectable-has-value ng-touched"]
allthreebuttons=//ion-item[@class='item md item-lines-none item-fill-none ion-focusable hydrated item-multiple-inputs']//div
DownloadFormat=(//ion-button[@class="md button button-solid ion-activatable ion-focusable hydrated"])[2]
message=//ion-toast[@class="md hydrated"]
uploadexcel=(//ion-button[@class="md button button-solid ion-activatable ion-focusable hydrated"])[3]
excelclose=(//ion-icon[@class="md hydrated"])[49]
text=//span[@style="margin-left: 17px;"]
header1=(//div[@class="block_center_content"])[2]
uploadbutton=//ion-button[@class="ion-color ion-color-primary md button button-solid ion-activatable ion-focusable hydrated"]
choosefile=//input[@class="ng-untouched ng-pristine ng-valid"]
uploadesuccesfully=//p[contains(text(), 'Upload Successfully')]
excellogdetials=//p[@style="font-family: nexa_bold; color: #ffffff; font-size: 15px; margin-left: 25px; text-align: center;"]
backbutton=(//img[@src="assets/imgs/ic_back.png"])[2]
uploadexcelheader=//p[contains(text(),' Uploaded Excels ')]
somthingwenwrong=//*[@id="alert-17-msg"]
ok2=//span[@class="alert-button-inner sc-ion-alert-md"]
selectfile=//div[@id="alert-16-msg"]
filter=(//ion-icon[@class="md hydrated"])[49]
filter_click=(//ion-button[@class="md button button-solid ion-activatable ion-focusable hydrated"])[7]
response=//ion-list-header[@class="md list-header-lines-none hydrated"]
showall=//*[@id="content"]/app-master-organisation-creation-excel-log-details-list/ion-content/div[1]/div/div/ion-list/ion-item/ion-select
showallist=//div[@class="alert-button-inner sc-ion-alert-md"]
showall_radiocheck=//*[@id="alert-input-18-0"]
upload_succesfully=//*[@id="alert-input-18-1"]
not_uploaded=//*[@id="alert-input-18-2"]
uploaded_excel_table=(//thead[@class="report-table__head"])[3]
table=(//table[@class="report-table"])[3]
uploaded_excel_tabledata=//*[@id="content"]/app-master-organisation-creation-excel-logs-list/ion-content/div/table/tbody/tr
download_button=//ion-button[@class="ion-color ion-color-primary md button button-solid ion-activatable ion-focusable hydrated"]
cancel=//ion-button[@class="ion-color ion-color-danger md button button-small button-round button-solid ion-activatable ion-focusable hydrated"]
ok3=//*[@id="ion-overlay-18"]/div[2]/div[4]/button[2]
excellog_table=//*[@id="content"]/app-master-organisation-creation-excel-log-details-list/ion-content/div[2]/table/thead
table_data=//*[@id="content"]/app-master-organisation-creation-excel-log-details-list/ion-content/div[2]/table/tbody
mandatory_data=//*[@id="content"]/app-master-organisation-creation-excel-log-details-list/ion-content/div[2]/table/tbody/tr/td[1]/div/p
excellog_table=(//table[@class="report-table"])[2]
nodatafound=//*[@id="content"]/app-master-organisation-creation-excel-log-details-list/ion-content/div[2]/h1
exportcredential=//*[@id="content"]/app-master-organisation-creation/ion-content/div/div[1]/div[2]/ion-button[4]
excelexport=(//ion-button[@class="md button button-solid ion-activatable ion-focusable hydrated"])[5]
log=(//ion-button[@class="md button button-solid ion-activatable ion-focusable hydrated"])[6]
bydefaultselectedchc=//div[@class="ionic-selectable-value-item"]
uploadedexcels=//*[@id="content"]/app-master-organisation-creation-excel-logs-list/ion-header/ion-toolbar/p
selectchc=//*[@id="chcFilter"]/div/div[1]/div/div[2]
selectbutton=//*[@id="chcFilter"]/div/button
checked=//ion-icon[@aria-label="checkmark circle"]
listheader=//*[@id="ion-overlay-13"]/ionic-selectable-modal/ion-header/ion-toolbar[1]/ion-title/span[2]
cancel3=//ion-button[@class="md button button-clear in-toolbar in-buttons ion-activatable ion-focusable hydrated"]
cancel4=//ion-button[@class="md button button-clear in-toolbar in-buttons ion-activatable ion-focusable hydrated"]
searchbar=//*[@id="ion-overlay-13"]/ionic-selectable-modal/ion-header/ion-toolbar[2]/ion-searchbar/div
click_chc_list=(//ion-label[@class="sc-ion-label-md-h sc-ion-label-md-s md hydrated"])[3]
click_chc_list1=(//ion-label[@class="sc-ion-label-md-h sc-ion-label-md-s md hydrated"])[7]
tabledata=//table[@class="report-table"]
nodatafound1=//h1[normalize-space()='No Data Found']
tabledata_varification_after_chc_Selection=//*[@id="content"]/app-master-organisation-creation/ion-content/div/div[4]/table/tbody
bydefault_table_data=//table[@class="report-table"]
search_input=//input[@class="searchbar-input sc-ion-searchbar-md"]
close_search=//button[@aria-label="reset"]
chillingcenter_list=//*[@id="ion-overlay-16"]/ionic-selectable-modal/ion-content/ion-list/ion-item-group/ion-item
Toggle_button=//*[@id="content"]/app-master-organisation-creation/ion-content/div/div[4]/table/tbody//ion-toggle
alert_model=//div[@class="alert-wrapper ion-overlay-wrapper sc-ion-alert-md"]
alert_model_text=//div[@class="alert-message sc-ion-alert-md"]
cancel1=(//span[@class="alert-button-inner sc-ion-alert-md"])[1]
yes=(//span[@class="alert-button-inner sc-ion-alert-md"])[2]
Succesfull_message=//div[@class="alert-message sc-ion-alert-md"]
ok1=//span[@class="alert-button-inner sc-ion-alert-md"]
toggle_off=//*[@id="content"]/app-master-organisation-creation/ion-content/div/div[4]/table/tbody/tr[1]/td[9]/ion-toggle
table_columns=//thead[@class="report-table__head"]
table_fields=//b[@style="margin-right: 10px; word-break: keep-all;"]
edit=//ion-icon[@name="create-outline"]
click_edit=//*[@id="content"]/app-master-organisation-creation/ion-content/div/div[4]/table/tbody/tr[12]/td[10]/ion-button
click_edit2=//*[@id="content"]/app-master-organisation-creation/ion-content/div/div[4]/table/tbody/tr[2]/td[10]/ion-button
edit_form_header=//*[@id="content"]/app-chilling-collection-farmer-edit/ion-header/ion-toolbar/div[2]/p
beckbutton_edit=//*[@id="content"]/app-chilling-collection-farmer-edit/ion-header/ion-toolbar/div[1]/img
Status=(//ion-label[@class="sc-ion-label-md-h sc-ion-label-md-s md hydrated"])[1]
activity=//div[@class="statusText"]
edit_form_data =//input[@placeholder="Enter Value"]
noneditable_element = //input[@class="native-input sc-ion-input-md"] 
form_fields=//ion-label[@class="ion-text-wrap sc-ion-label-md-h sc-ion-label-md-s md hydrated"]
edit_data=//input[@class="native-input sc-ion-input-md"]
Update_button=//ion-button[@class="md button button-small button-round button-solid ion-activatable ion-focusable hydrated"]
table_updated_data=//p[@style="margin: 0; display: flex; margin-bottom: 1rem; word-break: break-all;"]
update_succesfully_toast= //ion-toast[@class="md hydrated"]
cancelButton=//ion-button[@class="ion-color ion-color-danger md button button-small button-round button-solid ion-activatable ion-focusable hydrated"]
header_mainpage=//*[@id="content"]/app-master-organisation-creation/ion-header/ion-toolbar/div[2]/p
//////////////// User Master////////////////////// ////
