getstarted=//button[contains(text(),"Get Started")]
email=//input[@placeholder="Enter Login ID or Mobile Number"]
next=//button[contains(text()," Next ")]
password=//input[@placeholder="Password"]
customercode=//input[@placeholder="Customer Code"]
login=//button[contains(text(),"Login")]
menu=//img[@src="assets/imgs/ic_ham.png"]
master=(//ion-row[@class="ion-no-padding center_item md hydrated"])[3]
master=(//ion-row[@class="ion-no-padding center_item md hydrated"])[3]
userMasterHeader = //*[@id="content"]/app-user-master-usersummary/ion-header/ion-toolbar/div[2]/p
backButton=//*[@id="content"]/app-user-master-usersummary/ion-header/ion-toolbar/div[1]/img
inputSearch=//input[@class="searchbar-input sc-ion-searchbar-md"]
searchCloseButton=//ion-icon[@class="searchbar-clear-icon sc-ion-searchbar-md md hydrated"]
searchBar=//ion-searchbar[@class="sc-ion-searchbar-md-h sc-ion-searchbar-md-s md searchbar-left-aligned hydrated"]
addUsers=(//ion-button[@class="md button button-solid ion-activatable ion-focusable hydrated"])[1]
excelExport=(//ion-button[@class="md button button-solid ion-activatable ion-focusable hydrated"])[2]
Master=/html/body/app-root/ion-app/ion-menu/ion-content/ion-list/ion-item[2]/ion-grid/ion-row/ion-col[1]/ion-row
menuUserMaster=/html/body/app-root/ion-app/ion-menu/ion-content/ion-list/div[2]/ion-list/ion-item[4]/ion-grid/ion-row/p
userMasterHeader = (//div[@class="block_center_content"])[2]
navbutton=//img[@src="assets/imgs/ic_back.png"]
Dashboard=//div[@class="block_center_content"]
AddUser= (//ion-button[@class="md button button-solid ion-activatable ion-focusable hydrated"])[1]
userCreationForm=(//div[@class="block_center_content"])[3]
backButtonForm=(//div[@class="flex_center_content"])[4]
mandatoryField= //p[@style="text-align: right; color: red;"]
activeStatus=(//ion-label[@class="sc-ion-label-md-h sc-ion-label-md-s md hydrated"])[3]
ionToggle=//input[@name="ion-tg-0"]
formFields=//ion-label[@class="ion-text-wrap sc-ion-label-md-h sc-ion-label-md-s md hydrated"]
dairyFarm=//ion-select[@aria-label="Dairy Farm"]
name=//input[@placeholder="Enter Name"]
LoginID=//input[@placeholder="Generating User Login ..."]
password1=//input[@placeholder="Generating Password ..."]
gender= (//ion-select[@style="max-width: 100% !important; color: #000; margin-left: -9px;"])[2]
Roles=(//ion-select[@style="max-width: 100% !important; color: #000; margin-left: -9px;"])[3]
phone1=//input[@placeholder="Enter Phone No."]
email1=//input[@placeholder="Enter email ID"]
alertModel=//div[@class="alert-wrapper ion-overlay-wrapper sc-ion-alert-md"]
usertype_List=//div[@class="alert-radio-label sc-ion-alert-md"]
usertyperadio=//button[@class="select-interface-option md alert-radio-button alert-tappable alert-radio ion-focusable sc-ion-alert-md"]
cancelOk=//div[@class="alert-button-group sc-ion-alert-md"]
Cancel=(//span[@class="alert-button-inner sc-ion-alert-md"])[1]
Ok=//button[@class="alert-button ion-focusable ion-activatable sc-ion-alert-md"]
dairyFarmText=//ion-select[@class="ion-text-wrap ng-pristine md hydrated ng-valid ng-touched ion-pristine ion-valid ion-touched"]
collectionCenterOnModelPage=(//div[@class="alert-radio-label sc-ion-alert-md"])[2]
collectionCenterOnForm=//ion-select[@class="ion-text-wrap md hydrated ng-valid ng-touched ng-dirty ion-valid ion-touched ion-dirty"]
chillingCenterOnModelPage=(//div[@class="alert-radio-label sc-ion-alert-md"])[3]
chillingcenterOnForm=//ion-select[@class="ion-text-wrap md hydrated ng-valid ng-touched ng-dirty ion-valid ion-touched ion-dirty"]
selectMCC= //*[@id="content"]/app-user-master-adduser/ion-content/div/ion-card/ion-card-content/form/ion-grid/ion-row[2]/ion-col[3]/ion-select
gender=(//ion-select[@class="ion-text-wrap ng-untouched ng-pristine ng-valid md hydrated ion-untouched ion-pristine ion-valid"])[3]
genderList=//div[@class="alert-radio-label sc-ion-alert-md"]
checkRadioOnGender=//button[@role="radio"]
maleRadioClick=(//button[@class="select-interface-option ion-text-wrap md alert-radio-button alert-tappable alert-radio ion-focusable sc-ion-alert-md"])[2]
otherRadioClick=(//button[@class="select-interface-option ion-text-wrap md alert-radio-button alert-tappable alert-radio ion-focusable sc-ion-alert-md"])[3]
genderModel=//div[@class="alert-wrapper ion-overlay-wrapper sc-ion-alert-md"]
Female = //div[@class="alert-radio-label sc-ion-alert-md"]
genderInForm=//ion-select[@class="ion-text-wrap ng-valid md hydrated ng-touched ng-dirty ion-valid ion-touched ion-dirty"]
maleClick=(//button[@class="select-interface-option ion-text-wrap md alert-radio-button alert-tappable alert-radio ion-focusable sc-ion-alert-md"])[2]
otherClick=(//button[@class="select-interface-option ion-text-wrap md alert-radio-button alert-tappable alert-radio ion-focusable sc-ion-alert-md"])[3]
clickSelectRole=(//ion-select[@class="ion-text-wrap ng-untouched ng-pristine ng-valid md hydrated ion-untouched ion-pristine ion-valid"])[4]
selectRoleModel=//div[@class="alert-wrapper ion-overlay-wrapper sc-ion-alert-md"]
roleList(DairyFarm)=//div[@class="alert-checkbox-group sc-ion-alert-md"]
uncheckedCheckbox = //button[@class="select-interface-option md alert-tappable alert-checkbox alert-checkbox-button ion-focusable sc-ion-alert-md"]
DairyFarm=(//button[@class="select-interface-option md alert-tappable alert-checkbox alert-checkbox-button ion-focusable sc-ion-alert-md"])[1]
DeviationReport= (//button[@class="select-interface-option md alert-tappable alert-checkbox alert-checkbox-button ion-focusable sc-ion-alert-md"])[2]
ManualCorrectionCC=(//button[@class="select-interface-option md alert-tappable alert-checkbox alert-checkbox-button ion-focusable sc-ion-alert-md"])[3]
ManualCOrrectionCHC=(//button[@class="select-interface-option md alert-tappable alert-checkbox alert-checkbox-button ion-focusable sc-ion-alert-md"])[4]
selectRoleLabel=//*[@id="content"]/app-user-master-adduser/ion-content/div/ion-card/ion-card-content/form/ion-grid/ion-row[8]/ion-col[3]/ion-select
rolelists=//button[@class="select-interface-option md alert-tappable alert-checkbox alert-checkbox-button ion-focusable sc-ion-alert-md"]